/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Konfiguration': RouteRecordInfo<'/Konfiguration', '/Konfiguration', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/Projektanlage': RouteRecordInfo<'/Projektanlage', '/Projektanlage', Record<never, never>, Record<never, never>>,
    '/Projektneu': RouteRecordInfo<'/Projektneu', '/Projektneu', Record<never, never>, Record<never, never>>,
    '/ProTools': RouteRecordInfo<'/ProTools', '/ProTools', Record<never, never>, Record<never, never>>,
  }
}
