name: build-win
on:
  workflow_dispatch:
  push:
    tags: ['v*.*.*']

jobs:
  win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies (clean)
        run: npm ci

      - name: Build Windows (NSIS)
        run: |
          if (Test-Path dist) { Remove-Item dist -Recurse -Force }
          npm run dist:win
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-nsis
          path: dist/*