name: build-mac
on:
  workflow_dispatch:
  push:
    tags: ['v*.*.*']
jobs:
  mac:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies (clean)
        run: npm ci

      - name: Build macOS arm64
        run: |
          rm -rf dist
          npm run dist:mac:arm64
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'

      - name: Upload macOS arm64
        uses: actions/upload-artifact@v4
        with:
          name: macOS-arm64
          path: dist/*

      - name: Build macOS x64
        run: |
          rm -rf dist
          npm run dist:mac:x64
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'

      - name: Upload macOS x64
        uses: actions/upload-artifact@v4
        with:
          name: macOS-x64
          path: dist/*
