name: release-mac-arm64
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag (z.B. v0.2.1)'
        required: true
  push:
    tags: ['v*.*.*']

jobs:
  mac-arm64:
    runs-on: macos-14
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Fetch repo (no marketplace actions)
        run: |
          git init .
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch --depth=1 origin ${{ github.sha }}
          git checkout -qf ${{ github.sha }}

      - name: Ensure Node
        run: |
          node -v || (curl -fsSL https://get.volta.sh | bash -s -- --skip-setup && \
            echo 'export VOLTA_HOME="$HOME/.volta"' >> $GITHUB_ENV && \
            echo 'export PATH="$VOLTA_HOME/bin:$PATH"' >> $GITHUB_ENV && \
            export VOLTA_HOME="$HOME/.volta"; export PATH="$VOLTA_HOME/bin:$PATH"; volta install node@22)
          node -v
          corepack enable || true

      - name: Install deps (clean)
        run: |
          rm -rf node_modules dist out
          npm ci

      - name: Build macOS arm64
        run: npm run dist:mac:arm64

      - name: Create/Upload Release
        run: |
          TAG="${{ github.event.inputs.tag || github.ref_name }}"
          gh release view "$TAG" >/dev/null 2>&1 || gh release create "$TAG" --draft -t "$TAG" -n "Automated draft release"
          gh release upload "$TAG" dist/* --clobber