name: release-win
on:
  workflow_dispatch:
  push:
    tags: ['v*.*.*']

jobs:
  win:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Fetch repo
        shell: bash
        run: |
          git init .
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch --depth=1 origin ${{ github.sha }}
          git checkout -qf ${{ github.sha }}

      - name: Ensure Node (use preinstalled)
        shell: bash
        run: |
          node -v || true
          npm -v || true

      - name: Install deps (clean)
        shell: bash
        run: |
          rm -rf node_modules dist out || true
          npm ci

      - name: Build Windows (NSIS)
        shell: bash
        run: npm run dist:win

      - name: Upload to Release
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME}"
          gh release view "$TAG" >/dev/null 2>&1 || gh release create "$TAG" --draft -t "$TAG" -n "Automated draft release"
          gh release upload "$TAG" dist/* --clobber